import type { SourceDescriptor } from "./source-types";

const SOURCES: SourceDescriptor[] = [
  { id: "duckduckgo-html", name: "Public Web Search", description: "API-key-free HTML search used to discover public organization, community, recruiting, and market pages.", purposes: ["discover", "monitor"], method: "fetch", entityKinds: ["organization", "professional", "candidate", "talent_signal", "referral", "community_signal", "competitor_signal"], coverage: ["US"], apiKeyRequired: false, health: "ready", usageNote: "Use conservatively, cache results, and do not treat search snippets as verified facts." },
  { id: "public-website", name: "Organization Website", description: "Direct public website enrichment for contact details, service language, staff pages, careers, and referral information.", purposes: ["enrich", "verify", "monitor"], method: "fetch", entityKinds: ["organization", "professional", "candidate", "talent_signal", "referral", "competitor_signal"], coverage: ["US"], apiKeyRequired: false, health: "ready", usageNote: "Public pages only. Respect access controls and do not bypass authentication." },
  { id: "cms-nppes", name: "CMS NPPES / NPI", description: "Official CMS provider downloads with a live manifest adapter for the monthly baseline and weekly incremental files.", purposes: ["discover", "verify", "monitor"], method: "download", entityKinds: ["organization", "professional"], coverage: ["US"], apiKeyRequired: false, health: "ready", usageNote: "Use the monthly V2 file as the baseline and weekly V2 files as incremental updates. NPI issuance does not itself prove licensure or credential status." },
  { id: "nj-childcare-download", name: "NJ Licensed Child Care", description: "Official New Jersey DCF licensed child-care open data, filtered by city, ZIP, or county and merged into referral discovery.", purposes: ["discover", "verify", "monitor"], method: "download", entityKinds: ["organization", "referral"], coverage: ["NJ"], apiKeyRequired: false, health: "ready", usageNote: "Direct public CSV download; use license/inspection links as official evidence and separately enrich organization contact details." },
  { id: "state-childcare-browser", name: "Other State Child-Care Licensing", description: "Public state licensing sources that require state-specific adapters or browser navigation.", purposes: ["discover", "verify", "monitor"], method: "browser", entityKinds: ["organization", "referral"], coverage: ["MO"], apiKeyRequired: false, health: "degraded", usageNote: "Browser automation is used only on public interfaces and never to bypass access controls." },
  { id: "public-community", name: "Public Community Signals", description: "Area-level demand signals discovered from public forums, Reddit results, public resource pages, and indexable community discussions.", purposes: ["monitor"], method: "fetch", entityKinds: ["community_signal", "territory"], coverage: ["US"], apiKeyRequired: false, health: "ready", usageNote: "Aggregate to territory level. Do not create parent/child profiles or household disability targeting." },
  { id: "playwright-public-browser", name: "Playwright Public Browser", description: "Optional browser collector for public JS-rendered pages, forms, and pagination.", purposes: ["discover", "enrich", "verify", "monitor"], method: "browser", entityKinds: ["organization", "professional", "candidate", "talent_signal", "referral", "community_signal", "competitor_signal"], coverage: ["US"], apiKeyRequired: false, health: "degraded", usageNote: "Runtime activates only when the Playwright package and browser binary are installed. No login bypassing or private-group access." },
];

export function getSourceRegistry(): SourceDescriptor[] { return SOURCES; }
export function getSource(id: string) { return SOURCES.find((source) => source.id === id); }
